title: Implementing Inference with Mixture-of-Experts Transformers in FlexFlow
description: 15-618 Final Project at Carnegie Mellon University
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
include:
  - index.md